---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: article-pr-filechange
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    # pipelinesascode.tekton.dev/task: "git-clone"
    # How many runs we want to keep.
    pipelinesascode.tekton.dev/max-keep-runs: "2"
    # pipelinesascode.tekton.dev/on-cel-expression: |
      # event == "pull_request" && target_branch == "main" && "frontend/***".pathChanged()
spec:
  params:
    - name: repo_url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
  pipelineSpec:
    tasks:
      - name: noop-task
        taskSpec:
          steps:
            - name: noop-task
              image: ubuntu
              script: |
                #! /bin/bash
                echo {{ cloneurl }}
                sleep 20
                exit 0
