---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: article-push
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request, push]"
    pipelinesascode.tekton.dev/on-target-branch: "[test-jira-issue]"
    # pipelinesascode.tekton.dev/task: "git-clone"
    # How many runs we want to keep.
    pipelinesascode.tekton.dev/max-keep-runs: "2"
    # pipelinesascode.tekton.dev/on-cel-expression: |
      # event == "pull_request" && target_branch == "main" && "frontend/***".pathChanged()
spec:
  pipelineSpec:
    tasks:
      # Customize this task if you like, or just do a taskRef
      # to one of the hub task.
      - name: noop-task
        taskSpec:
          steps:
            - name: noop-task
              image: registry.access.redhat.com/ubi9/ubi-micro
              script: |
                sleep 30
                exit 0
